#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet -dict wallFilmRegion.topoSet
runApplication extrudeToRegionMesh -overwrite

paraFoam -touch
paraFoam -touch -region wallFilmRegion

#------------------------------------------------------------------------------
