#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0/lagrangian 0/uniform
rm -f O-O
rm -f electrostatic
rm -f constant/idList
rm -rf constant/polyMesh/sets
cleanCase

#------------------------------------------------------------------------------
