#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

runApplication blockMesh

runApplication -s 1  topoSet

runApplication subsetMesh -overwrite c0 -patch floatingObject -noFields

runApplication -s selectBottom \
    topoSet -dict topoSetDict-selectBottom

runApplication createPatch -overwrite

cp -R 0.orig 0 > /dev/null 2>&1

runApplication $application

#------------------------------------------------------------------------------
