#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication potentialFoam

# remove incompatible (volumetric) flux field
rm -f 0/phi

runApplication $(getApplication)

#------------------------------------------------------------------------------
