#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication extrudeMesh
runApplication topoSet
runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar -latestTime

runApplication foamPostProcess -latestTime -func "
    graphCell
    (
        name=graph,
        start=(3.4901 0 0),
        end=(3.4901 0.0096 0),
        fields=(alpha.gas T.liquid T.gas d.gas)
    )"
runApplication -append foamPostProcess -latestTime -func "
    patchSurface
    (
        name=patchWallBoilingProperties,
        patch=wall,
        surfaceFormat=raw,
        interpolate=false,
        fields=(dDeparture.liquid fDeparture.liquid nucleationSiteDensity.liquid wetFraction.liquid qQuenching.liquid qEvaporative.liquid)
    )"

if ! isTest "$@"
then
    ./validation/createGraphs
    ./validation/createWallBoilingPropertiesGraphs
fi

#------------------------------------------------------------------------------
