#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre

application=`getApplication`

runApplication -s wallFilmRegion decomposePar -region wallFilmRegion
runApplication -s primaryRegion  decomposePar

runParallel $application

runApplication -s wallFilmRegion reconstructPar -region wallFilmRegion
runApplication -s primaryRegion  reconstructPar

