#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake $targetType conformalVoronoiMesh
wmake $targetType conformalVoronoi2DMesh
wmake foamyQuadMesh
wmake foamyHexMesh
#wmake foamyHexMeshBackgroundMesh
#(cd foamyHexMeshSurfaceSimplify && ./Allwmake)
#wmake cellSizeAndAlignmentGrid


#------------------------------------------------------------------------------
