#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

\rm -rf 0
cp -r 0.org 0

runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel $application 4
runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
