#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

m4 system/blockMeshDict.m4 > system/blockMeshDict

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication `getApplication`

