#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

m4 constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication `getApplication`

