#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy propeller surfaces from resources directory
cp $FOAM_TUTORIALS/resources/geometry/propeller*.obj.gz constant/geometry/

# Mesh in parallel
${FOAM_APPBIN}/blockMesh
${FOAM_APPBIN}/surfaceFeatures
${FOAM_APPBIN}/decomposePar -noFields
${FOAM_APPBIN}/snappyHexMesh -overwrite

# Create the sliding patches
${FOAM_APPBIN}/createBaffles -overwrite
${FOAM_APPBIN}/splitBaffles -overwrite

# Renumber
${FOAM_APPBIN}/renumberMesh -noFields -overwrite

# Create non-conformal couples
${FOAM_APPBIN}/createNonConformalCouples -overwrite nonCouple1 nonCouple2

#------------------------------------------------------------------------------
