#!/bin/sh
#
# Build optional components (eg, may depend on third-party libraries)
#------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for compilation (at least for error catching)
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# build libccmio and create lnInclude directory
$WM_THIRD_PARTY_DIR/AllwmakeLibccmio

# if the library built properly, the headers should exist too
if [ -e $FOAM_EXT_LIBBIN/libccmio.so ]
then
    wmake $targetType ccm26ToFoam
fi

#------------------------------------------------------------------------------
