#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Do the Spalart-Allmaras steady-state case
(cd motorBike && foamRunTutorials)

# ----------------------------------------------------------------- end-of-file
