#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre

runApplication decomposePar

runParallel $(getApplication) 4

runApplication reconstructPar
