#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/panel/polyMesh
rm -rf constant/film/polyMesh

#------------------------------------------------------------------------------
