#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean
cleanVoFCase

# Un-merge the source case
path=$FOAM_TUTORIALS/incompressibleVoF
foamUnMergeCase $path/damBreak $path/damBreakLaminar $path/damBreakFine

#------------------------------------------------------------------------------
