#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

#- Test writing collated format
runApplication decomposePar -fileHandler collated
runParallel `getApplication` -fileHandler collated
runApplication reconstructPar -latestTime -fileHandler collated

#- Delete collated files
rm -rf processors

#- Test writing uncollated format
runApplication -s uncollated decomposePar -fileHandler uncollated
runParallel -s uncollated `getApplication` -fileHandler uncollated

#- Restart from uncollated
runParallel -s collated `getApplication` -fileHandler collated
runApplication -s collated reconstructPar -latestTime -fileHandler collated

#- Convert the parallel format to uncollated
runParallel foamFormatConvert -fileHandler uncollated

#------------------------------------------------------------------------------
