#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface
rm -f constant/geometry/NACA0012.obj.gz > /dev/null 2>&1

cleanCase

rm 0/Ma > /dev/null 2>&1
rm constant/geometry/boundaryLayer.obj > /dev/null 2>&1

#------------------------------------------------------------------------------
