#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

foamCleanTutorials cases
rm -rf 0/alpha.water 0/alpha.water.gz probes wallPressure pRefProbe

#------------------------------------------------------------------------------
