#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Meshing
runApplication blockMesh
runApplication surfaceFeatures
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite
runParallel splitMeshRegions -cellZones -overwrite

# Simulation
runParallel $(getApplication)

# Reconstruct
runApplication reconstructParMesh -constant -allRegions
runApplication reconstructPar -allRegions

# Post-process
paraFoam -touchAll

#------------------------------------------------------------------------------
