#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
foamDictionary system/controlDict -entry endTime -set 0.5
foamDictionary system/controlDict -entry startTime -set 0
