#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

## get ZOLTAN_ARCH_PATH
#if settings=`$WM_PROJECT_DIR/bin/foamEtcFile config/zoltan.sh`
#then
#    . $settings
#    echo "using ZOLTAN_ARCH_PATH=$ZOLTAN_ARCH_PATH"
#else
#    echo
#    echo "Error: no config/zoltan.sh settings"
#    echo
#fi


set -x

wmake $targetType renumberMethods

if [ -n "$BOOST_ARCH_PATH" ]
then
    wmake $targetType SloanRenumber
else
    echo
    echo "Skipping SloanRenumber"
    echo
fi


if [ -n "$ZOLTAN_ARCH_PATH" ]
then
    wmake $targetType zoltanRenumber
else
    echo
    echo "Skipping zoltanRenumber"
    echo
fi

# ----------------------------------------------------------------- end-of-file
