#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# If a test, try both extrusion strategies
if isTest "$@"
then
    cloneCase . extrudeFromInternalFaces
    cp -r All* include extrudeFromInternalFaces

    cloneCase . extrudeFromPatches
    cp -r All* include extrudeFromPatches

    (cd extrudeFromInternalFaces && ./Allrun extrudeFromInternalFaces)

    (cd extrudeFromPatches && ./Allrun extrudeFromPatches)

    exit
fi

# If not a test, just run one strategy
[ -n "$1" ] && strategy=$1 || strategy=extrudeFromInternalFaces

./Allmesh-$strategy

runApplication $(getApplication)

paraFoam -touchAll

#------------------------------------------------------------------------------
