#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=Test-fieldMapping

# Compile
wmake ..

runApplication blockMesh

runApplication $application

#------------------------------------------------------------------------------
