#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=Test-fieldMapping

# Compile
wmake ..

runApplication blockMesh

# Run with inflation
runApplication $application true
mv "log.$application" "log.$application-inflate"

# Run without inflation
runApplication $application false


# ----------------------------------------------------------------- end-of-file
