#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication splitMeshRegions -cellZonesOnly -overwrite

rm -f 0/cellToRegion 0/*/cellToRegion

runApplication createNonConformalCouples -overwrite

paraFoam -touchAll

runApplication $(getApplication)

#------------------------------------------------------------------------------
