#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType rigidBodyDynamics
wmake $targetType rigidBodyMotion_pointMeshMovers
wmake $targetType rigidBodyState
wmake $targetType rigidBodyForces

wmake $targetType sixDoFRigidBodyMotion
wmake $targetType sixDoFRigidBodyMotion_pointMeshMovers
wmake $targetType sixDoFRigidBodyState

#------------------------------------------------------------------------------
