#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=Test-hexRef8

# Compile
runApplication wmake ..

runApplication blockMesh

# Run with inflation
runApplication $application true
mv "log.$application" "log.$application-inflate"

# Run without inflation
runApplication $application false


#------------------------------------------------------------------------------
