#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -r constant/extendedFeatureEdgeMesh constant/internalDelaunayVertices > /dev/null 2>&1
rm constant/triSurface/*.eMesh > /dev/null 2>&1
rm constant/triSurface/*_orient* > /dev/null 2>&1
rm -r constant/polyMesh > /dev/null 2>&1
rm -r constant/polyMesh > /dev/null 2>&1
rm -r constant/tetDualMesh > /dev/null 2>&1

rm -r snapToSurface?.obj tetsToSnapTo.obj > /dev/null 2>&1

rm domain coneAndSphere > /dev/null 2>&1

rm -rf 0/

cleanCase

# ----------------------------------------------------------------- end-of-file
