#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

runApplication blockMesh
runApplication $application

# Get and transpose results
cp postProcessing/numberDensity/0/numberDensity.dat .
sed -i -e '1d' -e 's/# /#/g' numberDensity.dat
transposeFile numberDensity.dat > numberDensity.transposed.dat

cp postProcessing/volumeDensity/0/volumeDensity.dat .
sed -i -e '1d' -e 's/# /#/g' volumeDensity.dat
transposeFile volumeDensity.dat > volumeDensity.transposed.dat

# Create plot
( cd validation && ./createGraphs )

#------------------------------------------------------------------------------
