#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runApplication blockMesh

# Create faceZones for baffles and fan
runApplication topoSet

# Create baffles and the fields on them
runApplication createBaffles -overwrite -dict system/createBafflesDict.NCC

# Create non-conformal couplings
runApplication createNonConformalCouples -overwrite

runApplication $application

#------------------------------------------------------------------------------
