#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication $(getApplication)
runApplication checkMesh
runApplication foamToVTK

runApplication decomposePar
runParallel -s par $(getApplication)
runParallel -s par checkMesh
runParallel -s par foamToEnsight

runApplication reconstructParMesh -mergeTol 1e-6
# This will fail for any processors that does not have any local patches
# added so exclude that time
runApplication reconstructPar -time '0:0.01'
runApplication -s latestTime reconstructPar -latestTime

#------------------------------------------------------------------------------
