#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp system/controlDict.rhoCentralFoam system/controlDict

runApplication decomposePar
runParallel rhoCentralFoam
runApplication reconstructPar

#------------------------------------------------------------------------------
