#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase && rm -rf 0/phi 0/U 0/uniform 0/yPlus.liquid validation/*.eps

#------------------------------------------------------------------------------
