#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean

wclean libso fvModels/VoFTurbulenceDamping
wclean libso fvModels/VoFClouds
wclean libso fvModels/VoFSurfaceFilm
wclean libso fvModels/VoFCavitation
wclean libso fvModels/VoFSolidificationMeltingSource

#------------------------------------------------------------------------------
