#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`


# This case uses the #codeStream which is disabled by default. Enable for
# just this case.
MAIN_CONTROL_DICT=`foamEtcFile controlDict`
if [ -f "$MAIN_CONTROL_DICT" ]
then
    echo "Modifying ${MAIN_CONTROL_DICT} to enable allowSystemOperations"

    # Clean up on termination and on Ctrl-C
    trap 'mv ${MAIN_CONTROL_DICT}.$$ ${MAIN_CONTROL_DICT} 2>/dev/null; exit 0' \
        EXIT TERM INT
    cp ${MAIN_CONTROL_DICT} ${MAIN_CONTROL_DICT}.$$

    echo "Enabling allowSystemOperations in ${MAIN_CONTROL_DICT}."

    sed \
    -e s/"\(allowSystemOperations[ \t]*\)\([0-9]\);"/"\1 1;"/g \
    ${MAIN_CONTROL_DICT}.$$ > ${MAIN_CONTROL_DICT}
fi

cp -r 0.org 0 > /dev/null 2>&1
runApplication blockMesh
runApplication $application
runApplication streamFunction

# ----------------------------------------------------------------- end-of-file
