#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0
cp -r 0.org 0
runApplication blockMesh
runApplication changeDictionary
runApplication topoSet

runApplication PDRMesh -overwrite

# Run
runApplication `getApplication`

# ----------------------------------------------------------------- end-of-file
