#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso phaseSystem
wclean libso populationBalance
wclean libso momentumTransportModels
wclean libso thermophysicalTransportModels
wclean libso reactions

wclean

wclean libso fvModels
wclean libso functionObjects

#------------------------------------------------------------------------------
