#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso twoPhaseMixtureThermo
wclean libso surfaceTensionModels
wclean libso twoPhaseChange
wclean libso VoFphaseCompressibleMomentumTransportModels

wclean
wclean compressibleInterFilmFoam

#------------------------------------------------------------------------------
