#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmakeLnInclude interfacialModels
wmake libso twoPhaseSystem
wmake libso interfacialModels
wmake libso phaseCompressibleTurbulenceModels
wmake

# ----------------------------------------------------------------- end-of-file
