#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove surface
\rm -f constant/triSurface/bullet.stl.gz

cleanCase

# ----------------------------------------------------------------- end-of-file
