#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface
rm -f constant/triSurface/bullet.stl.gz

rm -f 0/phi

cleanCase

#------------------------------------------------------------------------------
