#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

decompose/Allwmake $*
reconstruct/Allwmake $*
wmake $makeType distributed


# ----------------------------------------------------------------- end-of-file
