#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

decompose/Allwmake $targetType $*
reconstruct/Allwmake $targetType $*
wmake $targetType distributed


#------------------------------------------------------------------------------
