#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# copy flange surface from resources directory
cp $FOAM_TUTORIALS/resources/geometry/flange.stl.gz constant/triSurface/

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite
