#                            -*- mode: org; -*-
#
#+TITLE:         Building the Doxygen help for OpenFOAM
#+AUTHOR:               The OpenFOAM Foundation
#+DATE:                     18th June 2016
#+LINK:                  http://www.openfoam.org
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2015-2016 OpenFOAM Foundation.

* Doxygen
  The HTML documentation of OpenFOAM can be built using the Doxygen software.
  Images in the documentation are generated using "dot", a program within the
  graphviz software package.  To build the documentation on the Ubuntu GNU/Linux
  system, for example, the user should install both =doxygen= and =graphviz=
  packages, e.g. by typing in a terminal window:

  + =sudo apt-get install doxygen graphviz=

  The Doxygen documentation will build automatically for a user that is
  configured to run OpenFOAM, i.e. has environment variables such as
  =$WM_PROJECT_DIR= set.  The user must also ensure they have write
  permission for the directory that Doxygen writes files to.

* Configuration
  The Doygen configuration file, Doxyfile, in the =$WM_PROJECT_DIR/doc/Doxygen=
  directory is configured to work with Doxygen versions 1.6.3-1.8.5.

  The Header, Footer, and Stylesheet are generated automatically:

  + =doxygen -w html header.html footer.html customdoxygen.css=

  See: https://www.stack.nl/~dimitri/doxygen/manual/customize.html

* Running Doxygen
  In the =$WM_PROJECT_DIR/doc/Doxygen= directory type
  + =./Allwmake=

  which will generate the =$WM_PROJECT_DIR/doc/Doxygen/html= directory
  containing the OpenFOAM source code documentation.  Load the =index.html= file
  into a browser, \e.g.\
  + =firefox html/index.html=
