/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Copyright (C) 2026 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::bMixture

Description
    Burnt gas mixture base class

SourceFiles
    bMixture.C

\*---------------------------------------------------------------------------*/

#ifndef bMixture_H
#define bMixture_H

#include "typeInfo.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                     Class bMixture Declaration
\*---------------------------------------------------------------------------*/

class bMixture
{
public:

    // Constructors

        //- Construct
        bMixture()
        {}

        //- Disallow default bitwise copy construction
        bMixture(const bMixture&) = delete;


    //- Destructor
    virtual ~bMixture()
    {}


    // Member Functions

        //- Return the mixture type name
        virtual const word& mixtureType() const = 0;


    // Member Operators

        //- Disallow default bitwise assignment
        void operator=(const bMixture&) = delete;
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
