#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

echo "Creating channel"
i=1
while [ "$i" -lt 3 ] ; do
    cp system/extrudeMeshDict.${i} system/extrudeMeshDict
    echo "Running extrudeMesh, instance" ${i}
    extrudeMesh > log.extrudeMesh.${i}
    i=$((i + 1))
done

#------------------------------------------------------------------------------
