#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

echo "--------"
echo "Cleaning tutorials ..."
echo "Removing backup files"
find . -type f \( -name "*~" -o -name "*.bak" \) -exec rm {} \;
find . \( -name core -o -name 'core.[1-9]*' \) -exec rm {} \;
find . \( -name '*.pvs' -o -name '*.OpenFOAM' \) -exec rm {} \;
rm logs testLoopReport > /dev/null 2>&1

foamCleanTutorials cases

echo "--------"

# ----------------------------------------------------------------- end-of-file
