#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Example with runApplication:
# - redirects all output to log.blockMesh
# - does *not* run if the log file already exists
runApplication blockMesh

runApplication decomposePar

# Example with runParallel to run in parallel
runParallel foamRun

runApplication reconstructPar

#------------------------------------------------------------------------------
