#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake $targetType cloud
wmake $targetType field
wmake $targetType forces
wmake $targetType fvTools
wmake $targetType IO
wmake $targetType jobControl
wmake $targetType systemCall
wmake $targetType utilities

# ----------------------------------------------------------------- end-of-file
