#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd hopperInitialState
cleanCase

cd ../hopperEmptying
cleanCase
rm -rf 0/lagrangian

# ----------------------------------------------------------------- end-of-file
