#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd hopperInitialState
runApplication blockMesh
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar -latestTime
cd ..

cd hopperEmptying
rm -rf 0
cp -r 0.orig 0
runApplication blockMesh
runApplication mapFields ../hopperInitialState -sourceTime latestTime
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar

#------------------------------------------------------------------------------
