#!/bin/sh

if ! which gnuplot > /dev/null 2>&1
then
    echo 'gnuplot not found - skipping graph creation' >&2
    exit 1
fi

gnuplot<<EOF
    set terminal postscript eps monochrome
    set output '../d.air_y.eps'

    set xlabel 'd (mm)'
    set ylabel 'y (m)'
    set yrange [0.05:]
    set key bottom center

    latestTime = system("foamListTimes -case .. -latestTime")

    file = '../postProcessing/singleGraph/'.latestTime.'/line_d.bubbles_p_alpha.air1_alpha.air2_alpha.air3_alpha.bubbles.xy'

    p0 = $(tail -n1 ../postProcessing/cellZoneAverage/0/volFieldValue.dat | awk '{print $2}')

    plot ''.file.'' u (\$2*1000):1 w l t 'prediction',\
    ''.file.'' u (0.003*(p0/\$3)**(1./3.)*1000):1 w l t 'exact result'

    set output '../alpha.air_y.eps'

    set xlabel '{/Symbol a} (-)'

    plot ''.file.'' u 4:1 w l t 'air1',\
    ''.file.'' u 5:1 w l t 'air2',\
    ''.file.'' u 6:1 w l t 'air3',\
    ''.file.'' u 7:1 w lp t 'air total'
EOF

#------------------------------------------------------------------------------
