#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

if [ -n "$CGAL_ARCH_PATH" ]
then
    wmake libso conformalVoronoiMesh
    wmake
    #wmake foamyHexMeshBackgroundMesh
    #(cd foamyHexMeshSurfaceSimplify && ./Allwmake)
    #wmake cellSizeAndAlignmentGrid
fi

# ----------------------------------------------------------------- end-of-file
