#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso DPMTurbulenceModels

wclean
wclean MPPICFoam

#------------------------------------------------------------------------------
