#!/bin/sh
cd ${0%/*} || exit 1

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType DPMTurbulenceModels

wmake $targetType
wmake $targetType MPPICFoam
