#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean time directories only

rm -rf *[1-9]*
rm -f log.* 2>/dev/null

# ----------------------------------------------------------------- end-of-file
