#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication splitMeshRegions -cellZonesOnly -overwrite

runApplication topoSet -region gas

paraFoam -region gas -touch
paraFoam -region solid -touch

runApplication decomposePar -allRegions

runParallel setFields -region gas

runParallel $(getApplication)

runApplication reconstructPar -allRegions -newTimes

#------------------------------------------------------------------------------
