#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create the underlying block mesh
runApplication blockMesh

# Create the set for the obstacles
runApplication topoSet

# Create the obstacles - add obstacle patches to wallFilm patch
runApplication subsetMesh c0 -patch wallFilm -overwrite -noFields

# Create a wallFilmRegion faceZone from the obstacles and floor
runApplication -s wallFilmRegion topoSet -dict topoSetDict.wallFilmRegion

# Create the wall film region from the wallFilmRegion faceZone via extrusion
runApplication extrudeToRegionMesh -overwrite

paraFoam -touch
paraFoam -touch -region wallFilmRegion

#------------------------------------------------------------------------------
