#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/filmRegion/polyMesh
rm -rf constant/pyrolysisRegion/polyMesh

rm -rf system/pyrolysisRegion/filmRegion

# ----------------------------------------------------------------- end-of-file
