#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0 chemFoam.out constant/reactions constant/speciesThermo \
   validation/OF_vs_CHEMKINII.eps validation/chemkinII

#------------------------------------------------------------------------------
