#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication createZones
runApplication setFields

runApplication decomposePar
runParallel foamRun

runApplication reconstructPar

#------------------------------------------------------------------------------
