#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

unset COMP_FLAGS LINK_FLAGS

#
# use readline if available
#
if [ -f /usr/include/readline/readline.h ]
then
    echo "Found <readline/readline.h>  --  enabling readline support."
    export COMP_FLAGS="-DHAS_READLINE"
    export LINK_FLAGS="-lreadline"
fi

wmake

# ----------------------------------------------------------------- end-of-file
