#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/reactions constant/speciesThermo 0/Qdot 0/uniform

#------------------------------------------------------------------------------
