#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="damBreak damBreakPorousBaffle weirOverflow waterChannel angledDuct"
loseCases="damBreakFine"

for case in $keepCases
do
    (cd $case && foamCleanTutorials)

    if [ "$case" = "damBreak" ]
    then
        cp $case/0/alpha.water.org $case/0/alpha.water
    fi

    if [ "$case" = "damBreakPorousBaffle" ]
    then
        cp $case/0/alpha.water.org $case/0/alpha.water
    fi

done

for case in $loseCases
do
    removeCase $case
done

# ----------------------------------------------------------------- end-of-file
