#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso multiphaseSystem
wclean libso interfacialModels
wclean

# ----------------------------------------------------------------- end-of-file
