#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="damBreak capillaryRise mixerVessel2D"
loseCases="damBreakFine"

for case in $keepCases
do
    (cd $case && foamCleanTutorials && rm -rf 0/alpha.water)
done

for case in $loseCases
do
    removeCase $case
done

# ----------------------------------------------------------------- end-of-file
