#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ -n "$FOAMY_HEX_MESH" ]
then
    ./Allmesh

    runApplication $(getApplication)
fi

#------------------------------------------------------------------------------
