#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0 > /dev/null 2>&1
runApplication blockMesh
#runApplication setSet -batch createObstacle.setSet
runApplication topoSet
runApplication subsetMesh -overwrite c0 -patch walls
runApplication setFields
runApplication `getApplication`

# ----------------------------------------------------------------- end-of-file
