#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/w3.eMesh > /dev/null 2>&1
rm -f constant/triSurface/w3.stl > /dev/null 2>&1
rm -rf sequencedVTK > /dev/null 2>&1

cleanCase

#------------------------------------------------------------------------------
