#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication star3ToFoam prostar/nacaAirfoil

sed -i -e 's/symmetry\([)]*;\)/empty\1/' constant/polyMesh/boundary

runApplication $application

# ----------------------------------------------------------------- end-of-file
