#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy mixerVessel surfaces from resources directory
cp $FOAM_TUTORIALS/resources/geometry/mixerVessel*.stl.gz constant/geometry/

# Meshing
runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
runApplication createBaffles -overwrite
runApplication splitBaffles -overwrite

#------------------------------------------------------------------------------
