#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

./Allmesh

# Initialize alpha
runApplication setFields

# Decompose
runApplication decomposePar -force

# Run
runParallel $application

# Reconstruct
runApplication reconstructPar -noFunctionObjects

#------------------------------------------------------------------------------
