#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

wmakeLnInclude interfacialModels
wmakeLnInclude interfacialCompositionModels
wmake libso phaseSystems
wmake libso interfacialModels
wmake libso interfacialCompositionModels
reactingTwoPhaseEulerFoam/Allwmake
reactingMultiphaseEulerFoam/Allwmake

# ----------------------------------------------------------------- end-of-file
