#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# copy motorbike surface from resources directory
cp $FOAM_TUTORIALS/resources/geometry/motorBike.obj.gz constant/geometry/

runApplication blockMesh
runApplication decomposePar -copyZero
runParallel snappyHexMesh

find . -type f -iname "*level*" -exec rm {} \;

runParallel renumberMesh

runParallel potentialFoam -initialiseUBCs

runParallel foamRun

#------------------------------------------------------------------------------
