#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp system/decomposeParDict.hierarchical system/decomposeParDict
runApplication decomposePar -copyZero

cp system/decomposeParDict.ptscotch system/decomposeParDict
runParallel snappyHexMesh -overwrite

find . -type f -iname "*level*" -exec rm {} \;

runParallel topoSet
runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar

#------------------------------------------------------------------------------
