#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
foamDictionary -entry "method" -set "hierarchical" system/decomposeParDict
runApplication decomposePar -copyZero
foamDictionary -entry "method" -set "ptscotch" system/decomposeParDict
runParallel snappyHexMesh -overwrite

runParallel topoSet
runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar -constant

#------------------------------------------------------------------------------
