#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmakeLnInclude ../incompressible/LES

wmake $makeType LESfilters
wmake $makeType LESdeltas

# ----------------------------------------------------------------- end-of-file
