#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd wingMotion_snappyHexMesh
cleanCase

cd ../wingMotion2D_simpleFoam
cleanCase
rm -rf 0

cd ../wingMotion2D_pimpleDyMFoam
cleanCase
rm -rf 0

