#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0 > /dev/null 2>&1

rm -rf constant/triSurface/blob.stl.gz > /dev/null 2>&1

rm -rf constant/cellAlignments > /dev/null 2>&1
rm -rf constant/targetCellSize > /dev/null 2>&1
rm -rf constant/internalDelaunayVertices > /dev/null 2>&1

rm -rf constant/backgroundMeshDecomposition/polyMesh/boundary > /dev/null 2>&1
rm -rf constant/backgroundMeshDecomposition/polyMesh/faces > /dev/null 2>&1
rm -rf constant/backgroundMeshDecomposition/polyMesh/neighbour > /dev/null 2>&1
rm -rf constant/backgroundMeshDecomposition/polyMesh/owner > /dev/null 2>&1
rm -rf constant/backgroundMeshDecomposition/polyMesh/points > /dev/null 2>&1

rm -rf snapToSurface?.obj > /dev/null 2>&1
rm -rf tetsToSnapTo.obj > /dev/null 2>&1


# ----------------------------------------------------------------- end-of-file
