#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication extrudeMesh
runApplication topoSet
runApplication setFields
runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
