#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType liquidProperties
wmake $makeType liquidMixtureProperties
wmake $makeType solidProperties
wmake $makeType solidMixtureProperties


# ----------------------------------------------------------------- end-of-file
