#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication surfaceFeatures
runApplication snappyHexMesh -overwrite
runApplication splitMeshRegions -cellZones -defaultRegionName fluid -overwrite

# ----------------------------------------------------------------- end-of-file
