#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

m4 system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh
runApplication topoSet
runApplication decomposePar
runParallel    $application
runApplication reconstructPar

( cd validation && ./createGraphs )

#------------------------------------------------------------------------------
