#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -rf PVdummy/Make

wclean libso vtkPVblockMesh
wclean libso vtkPVFoam

rm -rf Make PVblockMeshReader/Make PVFoamReader/Make

#------------------------------------------------------------------------------
