#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso vtkPVReaders
PVblockMeshReader/Allwclean
PVFoamReader/Allwclean

#------------------------------------------------------------------------------
