#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if [ -d "$ParaView_DIR" -a -r "$ParaView_DIR" ]
then
    wmake $targetType vtkPV3blockMesh

    if [ "$targetType" != "objects" ]
    then
        (
            cd PV3blockMeshReader
            mkdir -p Make/$WM_OPTIONS > /dev/null 2>&1
            cd Make/$WM_OPTIONS
            cmake ../..
            make
        )
    fi
fi

#------------------------------------------------------------------------------
